### ISSUE TITLE
Consider adding a LICENSE

### ISSUE THREAD

**Issue by ChiChou** [chyj4747/vue3-golden-layout-virtualcomponent#5]
It would be good if this project has an explcit license, so we can use it in the projects. Thanks!

----

您好，我的项目里想要参考这个项目的代码。
请问这个项目打算使用什么开源协议？非常感谢

**Comment by chyj4747** [comment]
随便用，没啥协议，本来就只是一段代码而已，连个项目都算不上
真正需要关注的协议应该是golden-layout的
